name: Build environment setup
description: Set up (Linux-only) build environment
author: Marten Lohstroh <marten@berkeley.edu>

runs:
  using: composite
  steps:
    - name: Prepare build environment
      uses: ./lingua-franca/.github/actions/prepare-build-env
    - name: Install VS Code
      run: |
        sudo apt update
        sudo apt install software-properties-common apt-transport-https wget
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        sudo apt install code
      shell: bash