# Main workflow for testing the Lingua Franca Visual Studio Code Extension 
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events.
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@check-versions
      - name: Install pylint
        run: python3 -m pip install pylint
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@check-versions
      # Uninstall operations are needed because we must test that the VS Code extension detects
      # which tools are present and responds appropriately.
      - uses: ./.github/actions/uninstall-dependencies
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-missing
        if: ${{ runner.os != 'Linux' }}
