# Main workflow for testing the Lingua Franca Visual Studio Code Extension 
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events.
  pull_request:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up build environment
        uses: ./actions/build-env
      - name: Build, deploy, and test the VS Code extension
        run: |
          npm install
          npm run test
