# Main workflow for testing the Lingua Franca Visual Studio Code Extension 
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events.
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@check-versions
      - name: Install pylint
        run: python3 -m pip install pylint
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing1:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@check-versions
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing1
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-missing1
        if: ${{ runner.os != 'Linux' }}
      - name: Install pylint
        run: python3 -m pip install pylint
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing0:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@check-versions
      - name: Uninstall Rust
        run: |
          rm -rf $(which rustc)
          rm -rf $(which cargo)
        if: runner.os == 'macOS'
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing0
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-missing0
        if: ${{ runner.os != 'Linux' }}
