name: Release new version

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: Build the VS Code extension
        run: |
          npm install
